### ISSUE TITLE
Error running reparser command (phpbb3.2)

### ISSUE THREAD

**Issue by rubencm** [board3/Board3-Portal#710]
\> bin/phpbbcli.php reparser:reparse

```
PHP Fatal error:  Uncaught Error: Call to undefined method Symfony\Component\Console\Formatter\OutputFormatter::escapeTrailingBackslash() in /var/www/xxx/vendor/symfony/console/Style/SymfonyStyle.php:91
Stack trace:
#0 /var/www/xxx-phpbb/phpbb/console/command/reparser/reparse.php(217): Symfony\Component\Console\Style\SymfonyStyle->section('Reparsing conta...')
#1 /var/www/xxx-phpbb/phpbb/console/command/reparser/reparse.php(152): phpbb\console\command\reparser\reparse->reparse('text_reparser.c...')
#2 /var/www/xxx-phpbb/ext/board3/portal/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(257): phpbb\console\command\reparser\reparse->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/www/xxx-phpbb/ext/board3/portal/vendor/symfony/console/Symfony/Component/Console/Application.php(882): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\ in /var/www/xxx-phpbb/vendor/symfony/console/Style/SymfonyStyle.php on line 91
```

I solved it by running this in extension folder, dont know if can cause other issues, but that error is gone

`composer update symfony/console --with-dependencies`

**Comment by marc1706** [comment]
Should be solved now that symfony is no longer one of the dependencies.
